[package]
name = "actix-csrf"
version = "0.1.0"
authors = ["Benoit Eudier <benoit.eudier@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version = "3", default_features = false, features = ["secure-cookies"] }
actix-service = "2"

serde = "1"
serde_derive = "1"
serde_json = "1"

futures = "0.3"
log = "0.4"
rand = "0.8"

# [dev-dependencies]
# regex = "1.0"
# reqwest = "0.9.18"
