[package]
name = "actix-csrf"
version = "0.1.0"
authors = ["Benoit Eudier <benoit.eudier@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version = "3", default_features = false, features = ["secure-cookies"] }

serde = "1"
serde_derive = "1"
serde_json = "1"

futures = "0.3"
log = "0.4"
rand = { version = "0.8", features = [ "std_rng" ] }

[dev-dependencies]
tokio = { version = "1", features = [ "macros", "rt-multi-thread" ] }