[package]
name = "actix-csrf"
version = "0.2.0"
authors = ["Benoit Eudier <benoit.eudier@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version = "4.0.0-beta.8", default_features = false, features = [ "cookies" ] }
base64 = "0.13"
cookie = "0.15"
rand = { version = "0.8", features = [ "std_rng" ] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = [ "macros", "rt-multi-thread" ] }