[package]
name = "actix-csrf"
version = "0.1.0"
authors = ["Benoit Eudier <benoit.eudier@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.8.2"
actix-rt = "0.2.2"
actix-web = "1.0.0"
actix-service = "0.4.1"
actix-http = "0.1.0"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1.5"
failure_derive = "0.1.5"

futures = "0.1"
log = "0.4.6"
rand = "0.6"


